"""empty message

Revision ID: edabdd349310
Revises: 
Create Date: 2026-06-27 12:34:47.196850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edabdd349310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlistitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlistitem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlistitem_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlistitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlistitem_name'))

    op.drop_table('wishlistitem')
    # ### end Alembic commands ###
